### ISSUE TITLE
add positivity check for define-datatype

### ISSUE THREAD

**Issue by stchang** [stchang/cur#2]

**Comment by wilbowma** [comment]
Fixed in my working branch `turnstile-merging`. https://github.com/wilbowma/cur/commit/39bbb15508390e5197703af46c16aac2396ec188

Will merge soon, but it breaks the sized type implementation, as sized types require a slightly different positivity checker.

**Comment by wilbowma** [comment]
Oh nevermind, this should be strictly positive according to Coq...

**Comment by wilbowma** [comment]
Okay this is fixed in that branch; will merge soon.

**Comment by stchang** [comment]
df6a7e9adec4fe1d9fd3fed52f1a49b675545b4e
